version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: io.servicetalk:servicetalk-concurrent-reactivestreams
    versions:
    - 0.39.0
